services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: |
      chmod +x render-build.sh && ./render-build.sh
      chmod +x render-deploy.sh && ./render-deploy.sh
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GOOGLE_API_KEY
        sync: false 